# Generated by Django 3.1.5 on 2021-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('in_id', models.IntegerField()),
                ('in_mname', models.CharField(max_length=10)),
                ('in_type', models.CharField(max_length=8)),
                ('in_url', models.CharField(max_length=50)),
                ('in_data', models.CharField(max_length=50)),
                ('in_tname', models.CharField(max_length=10)),
                ('in_expected_result', models.CharField(max_length=20)),
                ('in_actual_result', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pj_id', models.IntegerField()),
                ('pj_name', models.CharField(max_length=8)),
                ('pj_pname', models.CharField(max_length=8)),
                ('pj_tname', models.CharField(max_length=8)),
                ('pj_state', models.CharField(max_length=6)),
            ],
        ),
    ]
