# Generated by Django 2.2.7 on 2021-04-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_data',
            name='in_expected_result',
            field=models.IntegerField(),
        ),
    ]
