# Generated by Django 3.1.5 on 2021-02-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlatform_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_data',
            name='pj_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='project_data',
            name='pj_pname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='project_data',
            name='pj_tname',
            field=models.CharField(max_length=10),
        ),
    ]
